### ISSUE TITLE
a bytes-like object is required

### ISSUE THREAD

**Issue by DamonMerrick** [Oseid/Facebom#13]
![Screenshot_20200608-203934_Termux](https://user-images.githubusercontent.com/65680628/84062946-d1679000-a9c8-11ea-8ebf-a4208f3f7567.jpg)
 
What should i do?

**Comment by saidsaidouni** [comment]
same problem bro!!!!

**Comment by Oseid** [comment]
@saidsaidouni because you using **python3** to run this script,  the script require **python2** to work 
but now i have updated the script and fix this problem  now you can use both python 2,3 to run this script :)
so please re-clone it and try again :)
or run command: **git pull origin master**
Best regards. :)

**Comment by saidsaidouni** [comment]
@Oseid Thank you!! it works now!

**Comment by DamonMerrick** [comment]
wow, thank you, that's awesome!

**Comment by Oseid** [comment]
@saidsaidouni @DamonMerrick
 Glad to help and sorry i don't reply fast because i don't have time this days :(
